spring:
  thymeleaf:
    prefix: classpath:/static/
  profiles:
    active: "production"
  output:
    ansi:
      enabled: always
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:guaitil.p12
#    key-store-password: root1234
#    key-alias: guaitil
---
spring:
  profiles: "development"
  datasource:
    url: "jdbc:mysql://localhost/guaitil?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT-6"
    username: "root"
    password: "root"
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          time_zone: UTC

  security:
    jwt:
      token:
        secret-key : "secret-key"
        expire-length : 5
      header: "Authorization"


  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      enabled: false
server:
  port: 8080
---
spring:
  profiles: "production"
  datasource:
    url: "jdbc:mysql://localhost/guaitil?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT-6"
    username: "guaitil_user"
    password: "root124578"
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  security:
    jwt:
      token:
        secret-key : "gBHwqpF523Mp3mWd7p5deeeuG"
        expire-length : 5
      header: "Authorization"

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      enabled: false
server:
  port: 80