spring:
  profiles:
    active: "development"
  output:
    ansi:
      enabled: always
  datasource:
    url: "jdbc:mysql://localhost/guaitil?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT-6"
    testWhileIdle: true
    validationQuery: SELECT 1

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          time_zone: UTC
  security:
    jwt:
      token:
        expire-length: 5
      header: "Authorization"
server:
  port: 8080
user:
  password: "1234"
  email: "guaitiltour.cr@gmail.com"
  email-password: "Chorotega17"
reports-path: "reports"

guaitil-client:
  domain: "http://143.198.57.165:8080"
  cors: "*"

---
spring:
  profiles: "development"
  datasource:
    username: "root"
    password: "root"
  security:
    jwt:
      token:
        secret-key : "secret-key"
        expire-length : 30
---
user:
  password: "guaitilour!2021$"
spring:
  profiles: "sandbox"
  datasource:
    username: "guaitiltour_user_db"
    password: "guaitiltour!2021$db"
  security:
    jwt:
      token:
        secret-key : "gBHwqpF523Mp3mWdsdfsdfsd7p5deeeuG"
reports-path: "/root/guaitil-server/reports"
---
user:
  password: "guaitilour!2021$"
spring:
  profiles: "production"
  datasource:
    username: "guaitiltour_user_db"
    password: "guaitiltour!2021$db"
  security:
    jwt:
      token:
        secret-key : "gBHwqpF523Mp3mWd7p5deeeuG"
reports-path: "/root/guaitil-server/reports"
guaitil-client:
  domain: "https://guaitiltour.co.cr"
  cors: "*"