spring:
  profiles:
    active: "development"
  output:
    ansi:
      enabled: always
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          time_zone: UTC
  security:
    jwt:
      token:
        expire-length: 5
      header: "Authorization"
server:
  port: 8080
user:
  password: "1234"
  email: ${GUAITIL_USER_ADMIN_EMAIL}
  gmail-sender-email: ${GUAITIL_GMAIL_SENDER_EMAIL}
  gmail-sender-pass: ${GUAITIL_GMAIL_SENDER_PASS}
reports-path: "reports"

client-domain: "https://guaitiltour.co.cr"
server-domain: "https://server.guaitiltour.co.cr"
---
spring:
  profiles: "development"
  datasource:
    url: "jdbc:mysql://localhost/guaitil?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT-6"
    username: "root"
    password: "root"
  security:
    jwt:
      token:
        secret-key : "secret-key"
        expire-length : 30
---
spring:
  profiles: "production"
  datasource:
    url: ${GUAITIL_DATABASE_URL}
    username: ${GUAITIL_DATABASE_USER}
    password: ${GUAITIL_DATABASE_PASS}
  security:
    jwt:
      token:
        secret-key : ${GUAITIL_JWT_SECRET_KEY}
user:
  email: ${GUAITIL_USER_ADMIN_EMAIL}
  password: ${GUAITIL_USER_ADMIN_PASS}
  gmail-sender-email: ${GUAITIL_GMAIL_SENDER_EMAIL}
  gmail-sender-pass: ${GUAITIL_GMAIL_SENDER_PASS}
reports-path: ${GUAITIL_REPORTS_PATH}
guaitil-domain:
  client: ${GUAITIL_CLIENT_DOMAIN}
  server: ${GUAITIL_SERVER_DOMAIN}