package com.guaitilsoft.models.constant;

public enum TypeEmail {
    NEW_ACCOUNT_MEMBER,
    RESET_PASSWORD,
    NEW_ACCOUNT_ADMIN,
    ACTIVITY_MEMBER,
    ACTIVITY_ADMIN,
    RESERVATION_CLIENT,
    RESERVATION_CANCELED_CLIENT,
    NEW_PRODUCT,
    REVISED_PRODUCT
}
